package com.ceylonapz.aikeyboard

/**
 * Fast local emoji suggester using a HashMap.
 * Returns emoji suggestions in <1ms per word.
 * Supports multiple emojis per word and fuzzy category matching.
 */
class EmojiSuggester {

    // Main word → emoji map
    private val emojiMap: Map<String, List<String>> = buildMap {
        // ── Greetings & Emotions ───────────────────────────
        put("hello", listOf("👋", "🙋", "😊"))
        put("hi", listOf("👋", "🙋", "✌️"))
        put("hey", listOf("👋", "😏", "🙋"))
        put("bye", listOf("👋", "😢", "✌️"))
        put("goodbye", listOf("👋", "😢", "🫡"))
        put("welcome", listOf("🤗", "😊", "🙏"))
        put("thanks", listOf("🙏", "😊", "👍"))
        put("thank", listOf("🙏", "😊", "🤗"))
        put("please", listOf("🙏", "🥺", "😊"))
        put("sorry", listOf("😔", "🙏", "😢"))
        put("congrats", listOf("🎉", "🥳", "👏"))
        put("congratulations", listOf("🎉", "🥳", "🎊"))

        // ── Happy / Positive ───────────────────────────────
        put("happy", listOf("😊", "😃", "🥳"))
        put("great", listOf("👍", "🎉", "😊"))
        put("good", listOf("👍", "😊", "👌"))
        put("nice", listOf("👍", "😊", "✨"))
        put("awesome", listOf("🔥", "😎", "🙌"))
        put("amazing", listOf("🤩", "✨", "🔥"))
        put("wonderful", listOf("✨", "🤩", "😊"))
        put("beautiful", listOf("😍", "✨", "🌹"))
        put("perfect", listOf("👌", "💯", "✨"))
        put("excellent", listOf("💯", "🌟", "👏"))
        put("fantastic", listOf("🔥", "🤩", "🎉"))
        put("brilliant", listOf("💡", "🌟", "🔥"))
        put("cool", listOf("😎", "🆒", "❄️"))
        put("wow", listOf("😮", "🤩", "😲"))
        put("yay", listOf("🎉", "🥳", "🙌"))
        put("yes", listOf("✅", "👍", "🙌"))
        put("ok", listOf("👌", "✅", "👍"))
        put("okay", listOf("👌", "✅", "👍"))
        put("sure", listOf("👍", "✅", "👌"))
        put("agree", listOf("👍", "✅", "🤝"))
        put("right", listOf("👉", "✅", "👍"))
        put("true", listOf("✅", "💯", "👍"))
        put("fun", listOf("🎉", "😄", "🥳"))
        put("excited", listOf("🤩", "🎉", "😆"))
        put("proud", listOf("😊", "🥲", "💪"))
        put("blessed", listOf("🙏", "😇", "✨"))
        put("grateful", listOf("🙏", "😊", "💖"))
        put("lucky", listOf("🍀", "🎰", "✨"))

        // ── Sad / Negative ─────────────────────────────────
        put("sad", listOf("😢", "😔", "💔"))
        put("bad", listOf("👎", "😞", "💔"))
        put("terrible", listOf("😱", "💀", "👎"))
        put("horrible", listOf("😱", "🤮", "👎"))
        put("angry", listOf("😠", "🤬", "💢"))
        put("mad", listOf("😡", "🤬", "💢"))
        put("hate", listOf("😤", "👎", "💔"))
        put("upset", listOf("😢", "😤", "😞"))
        put("worried", listOf("😟", "😰", "🥺"))
        put("scared", listOf("😨", "😱", "🫣"))
        put("afraid", listOf("😨", "😰", "😱"))
        put("tired", listOf("😴", "😩", "🥱"))
        put("bored", listOf("😐", "🥱", "😒"))
        put("sick", listOf("🤒", "🤢", "😷"))
        put("hurt", listOf("🤕", "😢", "💔"))
        put("cry", listOf("😢", "😭", "💧"))
        put("crying", listOf("😭", "😢", "💧"))
        put("miss", listOf("😢", "💔", "🥺"))
        put("alone", listOf("😔", "🥺", "💔"))
        put("lonely", listOf("😔", "🥺", "💔"))
        put("stressed", listOf("😩", "😤", "🤯"))
        put("confused", listOf("😕", "🤔", "❓"))
        put("lost", listOf("😕", "🗺️", "❓"))
        put("no", listOf("❌", "🚫", "👎"))
        put("nope", listOf("❌", "🙅", "👎"))
        put("wrong", listOf("❌", "😬", "👎"))
        put("fail", listOf("❌", "💀", "😬"))
        put("oops", listOf("😬", "🫣", "😅"))

        // ── Love & Relationships ───────────────────────────
        put("love", listOf("❤️", "😍", "💕"))
        put("heart", listOf("❤️", "💖", "💗"))
        put("kiss", listOf("😘", "💋", "😗"))
        put("hug", listOf("🤗", "🫂", "💕"))
        put("baby", listOf("👶", "🍼", "💕"))
        put("friend", listOf("🤝", "👫", "💛"))
        put("family", listOf("👨‍👩‍👧‍👦", "🏠", "❤️"))
        put("wife", listOf("👩", "❤️", "💑"))
        put("husband", listOf("👨", "❤️", "💑"))
        put("boyfriend", listOf("👨", "❤️", "💕"))
        put("girlfriend", listOf("👩", "❤️", "💕"))
        put("date", listOf("📅", "💕", "🌹"))
        put("wedding", listOf("💒", "💍", "👰"))
        put("marry", listOf("💍", "💒", "❤️"))
        put("ring", listOf("💍", "🔔", "⭕"))

        // ── Food & Drink ───────────────────────────────────
        put("food", listOf("🍔", "🍕", "🍽️"))
        put("eat", listOf("🍽️", "😋", "🍴"))
        put("eating", listOf("😋", "🍽️", "🍴"))
        put("hungry", listOf("😋", "🍔", "🤤"))
        put("delicious", listOf("😋", "🤤", "👨‍🍳"))
        put("yummy", listOf("😋", "🤤", "👅"))
        put("cook", listOf("👨‍🍳", "🍳", "🔥"))
        put("cooking", listOf("👨‍🍳", "🍳", "🔥"))
        put("breakfast", listOf("🍳", "🥞", "☕"))
        put("lunch", listOf("🍔", "🥪", "🍽️"))
        put("dinner", listOf("🍽️", "🍷", "🥘"))
        put("pizza", listOf("🍕", "😋", "🧀"))
        put("burger", listOf("🍔", "😋", "🍟"))
        put("chicken", listOf("🍗", "🐔", "😋"))
        put("rice", listOf("🍚", "🍛", "🍱"))
        put("cake", listOf("🎂", "🍰", "🧁"))
        put("chocolate", listOf("🍫", "🤤", "😋"))
        put("ice", listOf("🧊", "❄️", "🍦"))
        put("icecream", listOf("🍦", "🍨", "😋"))
        put("fruit", listOf("🍎", "🍊", "🍇"))
        put("apple", listOf("🍎", "🍏", "📱"))
        put("coffee", listOf("☕", "🫖", "😊"))
        put("tea", listOf("🍵", "🫖", "☕"))
        put("water", listOf("💧", "🚰", "🌊"))
        put("beer", listOf("🍺", "🍻", "🥂"))
        put("wine", listOf("🍷", "🥂", "🍇"))
        put("drink", listOf("🍹", "🥤", "🍺"))
        put("cheers", listOf("🥂", "🍻", "🎉"))

        // ── Weather & Nature ───────────────────────────────
        put("sun", listOf("☀️", "🌞", "🌅"))
        put("sunny", listOf("☀️", "🌞", "😎"))
        put("rain", listOf("🌧️", "☔", "💧"))
        put("raining", listOf("🌧️", "☔", "💧"))
        put("snow", listOf("❄️", "⛄", "🌨️"))
        put("cold", listOf("🥶", "❄️", "🧊"))
        put("hot", listOf("🥵", "🔥", "☀️"))
        put("warm", listOf("🌡️", "☀️", "😊"))
        put("wind", listOf("💨", "🌬️", "🍃"))
        put("storm", listOf("⛈️", "🌩️", "💨"))
        put("cloud", listOf("☁️", "⛅", "🌥️"))
        put("moon", listOf("🌙", "🌕", "🌜"))
        put("star", listOf("⭐", "🌟", "✨"))
        put("stars", listOf("✨", "🌟", "⭐"))
        put("flower", listOf("🌸", "🌹", "🌺"))
        put("tree", listOf("🌳", "🌲", "🌴"))
        put("ocean", listOf("🌊", "🏖️", "🐚"))
        put("beach", listOf("🏖️", "🌊", "☀️"))
        put("mountain", listOf("🏔️", "⛰️", "🗻"))
        put("fire", listOf("🔥", "🧯", "🚒"))
        put("earth", listOf("🌍", "🌎", "🌏"))
        put("world", listOf("🌍", "🗺️", "🌎"))
        put("nature", listOf("🌿", "🍃", "🌳"))
        put("garden", listOf("🌻", "🌷", "🏡"))
        put("rainbow", listOf("🌈", "✨", "😊"))

        // ── Animals ────────────────────────────────────────
        put("dog", listOf("🐕", "🐶", "🦮"))
        put("cat", listOf("🐱", "🐈", "😺"))
        put("bird", listOf("🐦", "🕊️", "🦅"))
        put("fish", listOf("🐟", "🐠", "🎣"))
        put("bear", listOf("🐻", "🧸", "🐼"))
        put("lion", listOf("🦁", "👑", "🐾"))
        put("monkey", listOf("🐒", "🐵", "🙈"))
        put("horse", listOf("🐴", "🏇", "🐎"))
        put("rabbit", listOf("🐰", "🐇", "🥕"))
        put("pig", listOf("🐷", "🐖", "🐽"))
        put("cow", listOf("🐄", "🐮", "🥛"))
        put("butterfly", listOf("🦋", "🌸", "✨"))
        put("snake", listOf("🐍", "😱", "🐉"))
        put("elephant", listOf("🐘", "🦣", "🐾"))

        // ── Activities & Sports ────────────────────────────
        put("run", listOf("🏃", "👟", "💨"))
        put("running", listOf("🏃", "👟", "💪"))
        put("walk", listOf("🚶", "👟", "🌳"))
        put("gym", listOf("💪", "🏋️", "🔥"))
        put("exercise", listOf("💪", "🏃", "🔥"))
        put("workout", listOf("💪", "🏋️", "🔥"))
        put("football", listOf("⚽", "🏈", "🏟️"))
        put("soccer", listOf("⚽", "🏟️", "⚽"))
        put("basketball", listOf("🏀", "⛹️", "🏟️"))
        put("tennis", listOf("🎾", "🏸", "🏆"))
        put("swim", listOf("🏊", "💦", "🌊"))
        put("swimming", listOf("🏊", "💦", "🌊"))
        put("dance", listOf("💃", "🕺", "🎵"))
        put("dancing", listOf("💃", "🕺", "🎶"))
        put("game", listOf("🎮", "🕹️", "🎲"))
        put("play", listOf("🎮", "▶️", "🎯"))
        put("win", listOf("🏆", "🥇", "🎉"))
        put("winner", listOf("🏆", "🥇", "👑"))
        put("lose", listOf("😞", "👎", "💔"))
        put("race", listOf("🏁", "🏃", "🏎️"))
        put("goal", listOf("🎯", "⚽", "🥅"))
        put("champion", listOf("🏆", "👑", "🥇"))

        // ── Work & Study ───────────────────────────────────
        put("work", listOf("💼", "💻", "⚒️"))
        put("working", listOf("💼", "💻", "⚒️"))
        put("job", listOf("💼", "👔", "💰"))
        put("office", listOf("🏢", "💼", "🖥️"))
        put("meeting", listOf("🤝", "📊", "💼"))
        put("email", listOf("📧", "✉️", "💻"))
        put("call", listOf("📞", "📱", "🤙"))
        put("phone", listOf("📱", "📞", "🤳"))
        put("study", listOf("📚", "✏️", "🎓"))
        put("studying", listOf("📚", "✏️", "📖"))
        put("school", listOf("🏫", "📚", "🎒"))
        put("university", listOf("🎓", "🏫", "📚"))
        put("college", listOf("🎓", "🏫", "📚"))
        put("exam", listOf("📝", "😰", "✏️"))
        put("test", listOf("📝", "✅", "🧪"))
        put("book", listOf("📖", "📚", "📕"))
        put("read", listOf("📖", "📚", "👓"))
        put("write", listOf("✍️", "📝", "✏️"))
        put("idea", listOf("💡", "🤔", "✨"))
        put("think", listOf("🤔", "💭", "💡"))
        put("thinking", listOf("🤔", "💭", "🧠"))
        put("learn", listOf("📚", "🧠", "💡"))
        put("brain", listOf("🧠", "💡", "🤓"))
        put("smart", listOf("🧠", "🤓", "💡"))

        // ── Travel & Places ────────────────────────────────
        put("travel", listOf("✈️", "🌍", "🧳"))
        put("trip", listOf("✈️", "🧳", "🏖️"))
        put("vacation", listOf("🏖️", "✈️", "🌴"))
        put("holiday", listOf("🎄", "🏖️", "✈️"))
        put("flight", listOf("✈️", "🛫", "🛬"))
        put("car", listOf("🚗", "🏎️", "🚙"))
        put("drive", listOf("🚗", "🏎️", "🛣️"))
        put("driving", listOf("🚗", "🛣️", "🏎️"))
        put("bus", listOf("🚌", "🚏", "🚍"))
        put("train", listOf("🚆", "🚂", "🚉"))
        put("home", listOf("🏠", "🏡", "🏠"))
        put("house", listOf("🏠", "🏡", "🏘️"))
        put("hotel", listOf("🏨", "🛏️", "🧳"))
        put("city", listOf("🏙️", "🌆", "🏢"))
        put("country", listOf("🌍", "🏞️", "🗺️"))
        put("map", listOf("🗺️", "📍", "🧭"))
        put("hospital", listOf("🏥", "🚑", "💊"))

        // ── Time ───────────────────────────────────────────
        put("morning", listOf("🌅", "☀️", "☕"))
        put("night", listOf("🌙", "🌃", "😴"))
        put("evening", listOf("🌆", "🌙", "🌇"))
        put("today", listOf("📅", "☀️", "📆"))
        put("tomorrow", listOf("📅", "🔜", "⏭️"))
        put("yesterday", listOf("📅", "⏮️", "🔙"))
        put("weekend", listOf("🎉", "🥳", "😎"))
        put("birthday", listOf("🎂", "🎉", "🥳"))
        put("party", listOf("🎉", "🥳", "🎊"))
        put("christmas", listOf("🎄", "🎅", "🎁"))
        put("new year", listOf("🎆", "🥂", "🎉"))
        put("halloween", listOf("🎃", "👻", "🦇"))
        put("summer", listOf("☀️", "🏖️", "🌴"))
        put("winter", listOf("❄️", "⛄", "🧣"))
        put("spring", listOf("🌸", "🌷", "🦋"))
        put("autumn", listOf("🍂", "🍁", "🎃"))
        put("fall", listOf("🍂", "🍁", "🎃"))
        put("fast", listOf("⚡", "💨", "🏃"))
        put("slow", listOf("🐢", "🐌", "⏳"))
        put("wait", listOf("⏳", "⌛", "🤞"))
        put("waiting", listOf("⏳", "⌛", "😤"))
        put("late", listOf("⏰", "😬", "🏃"))
        put("early", listOf("⏰", "🌅", "👍"))
        put("time", listOf("⏰", "🕐", "⌛"))
        put("soon", listOf("🔜", "⏳", "🤞"))
        put("now", listOf("⏰", "👉", "‼️"))
        put("forever", listOf("♾️", "💕", "✨"))

        // ── Money & Shopping ───────────────────────────────
        put("money", listOf("💰", "💵", "🤑"))
        put("pay", listOf("💳", "💰", "💵"))
        put("buy", listOf("🛒", "💳", "🛍️"))
        put("shop", listOf("🛍️", "🛒", "💳"))
        put("shopping", listOf("🛍️", "🛒", "💸"))
        put("price", listOf("💰", "🏷️", "💵"))
        put("cheap", listOf("💸", "👍", "🤑"))
        put("expensive", listOf("💸", "😱", "💰"))
        put("rich", listOf("🤑", "💰", "💎"))
        put("poor", listOf("😢", "💸", "😔"))
        put("gift", listOf("🎁", "🎀", "💝"))
        put("present", listOf("🎁", "🎀", "🎉"))
        put("sale", listOf("🏷️", "💸", "🛍️"))
        put("free", listOf("🆓", "🎉", "💸"))

        // ── Tech ───────────────────────────────────────────
        put("computer", listOf("💻", "🖥️", "⌨️"))
        put("laptop", listOf("💻", "🖥️", "👨‍💻"))
        put("internet", listOf("🌐", "📶", "💻"))
        put("code", listOf("💻", "👨‍💻", "⌨️"))
        put("coding", listOf("👨‍💻", "💻", "⌨️"))
        put("program", listOf("💻", "👨‍💻", "🖥️"))
        put("app", listOf("📱", "💻", "📲"))
        put("website", listOf("🌐", "💻", "🔗"))
        put("robot", listOf("🤖", "🦾", "💻"))
        put("ai", listOf("🤖", "🧠", "💡"))
        put("data", listOf("📊", "💾", "📈"))
        put("bug", listOf("🐛", "🐞", "💻"))
        put("update", listOf("🔄", "📲", "⬆️"))
        put("download", listOf("⬇️", "📥", "💾"))
        put("upload", listOf("⬆️", "📤", "☁️"))
        put("password", listOf("🔐", "🔑", "🔒"))
        put("search", listOf("🔍", "🔎", "🕵️"))
        put("photo", listOf("📸", "🖼️", "📷"))
        put("picture", listOf("🖼️", "📸", "📷"))
        put("camera", listOf("📷", "📸", "🤳"))
        put("video", listOf("🎬", "📹", "▶️"))
        put("music", listOf("🎵", "🎶", "🎧"))
        put("song", listOf("🎵", "🎤", "🎶"))
        put("movie", listOf("🎬", "🍿", "📽️"))
        put("tv", listOf("📺", "🍿", "🎬"))

        // ── People & Body ──────────────────────────────────
        put("man", listOf("👨", "🧔", "🙋‍♂️"))
        put("woman", listOf("👩", "🙋‍♀️", "💃"))
        put("boy", listOf("👦", "🙋‍♂️", "😊"))
        put("girl", listOf("👧", "🙋‍♀️", "😊"))
        put("kid", listOf("🧒", "👶", "😊"))
        put("people", listOf("👥", "🧑‍🤝‍🧑", "👫"))
        put("king", listOf("👑", "🤴", "♚"))
        put("queen", listOf("👑", "👸", "♛"))
        put("doctor", listOf("👨‍⚕️", "🏥", "💊"))
        put("teacher", listOf("👩‍🏫", "📚", "🎓"))
        put("police", listOf("👮", "🚔", "🚨"))
        put("strong", listOf("💪", "🦾", "🏋️"))
        put("power", listOf("💪", "⚡", "🔋"))
        put("sleep", listOf("😴", "💤", "🛏️"))
        put("sleeping", listOf("😴", "💤", "🌙"))
        put("dream", listOf("💭", "🌙", "✨"))
        put("eyes", listOf("👀", "👁️", "😍"))
        put("look", listOf("👀", "👁️", "🔍"))
        put("hand", listOf("✋", "🤚", "👋"))
        put("clap", listOf("👏", "🙌", "🎉"))

        // ── Misc ───────────────────────────────────────────
        put("new", listOf("🆕", "✨", "🎉"))
        put("old", listOf("👴", "📜", "🏛️"))
        put("big", listOf("🐘", "😮", "💪"))
        put("small", listOf("🐜", "🤏", "🔬"))
        put("important", listOf("❗", "⭐", "📌"))
        put("help", listOf("🆘", "🙏", "🤝"))
        put("problem", listOf("😟", "❌", "🤔"))
        put("question", listOf("❓", "🤔", "💭"))
        put("answer", listOf("✅", "💬", "💡"))
        put("secret", listOf("🤫", "🔐", "🤐"))
        put("surprise", listOf("😮", "🎉", "🤯"))
        put("magic", listOf("✨", "🪄", "🎩"))
        put("luck", listOf("🍀", "🤞", "✨"))
        put("danger", listOf("⚠️", "🚨", "☠️"))
        put("warning", listOf("⚠️", "🚨", "❗"))
        put("stop", listOf("🛑", "✋", "🚫"))
        put("go", listOf("🟢", "▶️", "🏃"))
        put("up", listOf("⬆️", "👆", "📈"))
        put("down", listOf("⬇️", "👇", "📉"))
        put("laugh", listOf("😂", "🤣", "😆"))
        put("lol", listOf("😂", "🤣", "😆"))
        put("haha", listOf("😂", "🤣", "😄"))
        put("joke", listOf("😂", "🤡", "😜"))
        put("crazy", listOf("🤪", "😜", "🤯"))
        put("dead", listOf("💀", "☠️", "😵"))
        put("die", listOf("💀", "☠️", "😵"))
        put("ghost", listOf("👻", "🫥", "💀"))
        put("sick", listOf("🤒", "🤢", "😷"))
        put("king", listOf("👑", "🤴", "🦁"))
        put("flag", listOf("🚩", "🏁", "🏳️"))
        put("check", listOf("✅", "☑️", "✔️"))
        put("done", listOf("✅", "👍", "🎉"))
        put("ready", listOf("✅", "💪", "🏁"))
        put("start", listOf("▶️", "🏁", "🟢"))
        put("finish", listOf("🏁", "✅", "🎉"))
        put("end", listOf("🔚", "🏁", "✅"))
    }

    /**
     * Get emoji suggestions for the last typed word.
     * Returns up to 3 emojis or empty list if no match.
     */
    fun suggest(word: String): List<String> {
        val clean = word.lowercase()
            .trim()
            .removeSuffix(".")
            .removeSuffix(",")
            .removeSuffix("?")
            .removeSuffix("!")
            .removeSuffix("'s")
            .removeSuffix("ing")  // fallback: "running" → check "runn" then "run"
            .trim()

        // Direct match first
        emojiMap[word.lowercase().trim().removeSuffix(".").removeSuffix(",")
            .removeSuffix("?").removeSuffix("!")]?.let { return it }

        // Try without common suffixes
        emojiMap[clean]?.let { return it }

        // Try removing "ing", "ed", "s", "ly"
        val stemmed = word.lowercase().trim()
            .removeSuffix(".").removeSuffix(",")
            .removeSuffix("?").removeSuffix("!")
        val stems = listOf(
            stemmed.removeSuffix("ing"),
            stemmed.removeSuffix("ed"),
            stemmed.removeSuffix("s"),
            stemmed.removeSuffix("ly"),
            stemmed.removeSuffix("tion"),
            stemmed.removeSuffix("ness"),
        )
        for (stem in stems) {
            emojiMap[stem]?.let { return it }
        }

        return emptyList()
    }
}